
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 38;
  public static final int LBRACKET = 17;
  public static final int UMINUS = 5;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int INT = 39;
  public static final int LESS = 31;
  public static final int MINUS = 4;
  public static final int RPAREN = 8;
  public static final int OROR = 27;
  public static final int NOT = 21;
  public static final int LESSEQUAL = 32;
  public static final int BOOL = 40;
  public static final int COMMA = 19;
  public static final int EQUALEQUAL = 28;
  public static final int DIV = 41;
  public static final int ANDAND = 26;
  public static final int DIFFERENT = 29;
  public static final int PLUS = 3;
  public static final int IF = 25;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int RBRACKET = 18;
  public static final int EQUAL = 20;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int NUMBER = 14;
  public static final int CIN = 12;
  public static final int BIGGER = 30;
  public static final int VOID = 10;
  public static final int TIMES = 6;
  public static final int ELSE = 9;
  public static final int DOUBLEQUOTE = 13;
  public static final int COUT = 11;
  public static final int LSQUARE = 15;
  public static final int RSQUARE = 16;
  public static final int WHILE = 24;
  public static final int BIGGEREQUAL = 33;
  public static final int LSHIFT = 35;
  public static final int FALSE = 23;
  public static final int RSHIFT = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "ELSE",
  "VOID",
  "COUT",
  "CIN",
  "DOUBLEQUOTE",
  "NUMBER",
  "LSQUARE",
  "RSQUARE",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "EQUAL",
  "NOT",
  "TRUE",
  "FALSE",
  "WHILE",
  "IF",
  "ANDAND",
  "OROR",
  "EQUALEQUAL",
  "DIFFERENT",
  "BIGGER",
  "LESS",
  "LESSEQUAL",
  "BIGGEREQUAL",
  "RETURN",
  "LSHIFT",
  "RSHIFT",
  "ID",
  "STRING_LITERAL",
  "INT",
  "BOOL",
  "DIV"
  };
}

